<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Name>NNekoWeaponIcons</Name>
        <Author>NaughtyNeko</Author>
        <Punchline>Can't seem to find the right weapon for the job?  This may help!</Punchline>
        <Description>Adds a Clas/Job Icon Overlay in Armoury Chest.  Split from VIWI plugin's Kitchen Sink module.</Description>
        <Tags>NNeko,NaughtyNeko,UI,Other</Tags>
        <WarningLevel>4</WarningLevel>
        <PackageLicenseExpression>APGL-3.0-or-later</PackageLicenseExpression>
        <Deterministic>true</Deterministic>
        <CopyLocalLockfileAssemblies>true</CopyLocalLockfileAssemblies>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoWarn>$(NoWarn);IDE1006,CS8618,MSB3270</NoWarn>
        <DalamudUseLocalPluginJson>true</DalamudUseLocalPluginJson>
        <Version>0.0.1.8</Version>
        <AssemblyVersion>0.0.1.8</AssemblyVersion>
        <FileVersion>0.0.1.8</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Include="NNekoWeaponIcons.json" CopyToOutputDirectory="Always" />
        <Content Include="Data\NNeko.png" CopyToOutputDirectory="Always" />
        <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
    </ItemGroup>
</Project>