<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/14.0.2">
  <PropertyGroup>
    <Name>NNekoWeaponIcons</Name>
    <Author>NaughtyNeko</Author>
    <Punchline>Can't seem to find the right weapon for the job?  This may help!</Punchline>
    <Description>Adds a Clas/Job Icon Overlay in Armoury Chest.  Split from VIWI plugin's Kitchen Sink module.</Description>
    <Version>0.1</Version>
    <Tags>NNeko,NaughtyNeko,UI,Utility,Other</Tags>
    <WarningLevel>4</WarningLevel>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
  </PropertyGroup>

    <PropertyGroup>
        <Deterministic>true</Deterministic>
        <CopyLocalLockfileAssemblies>true</CopyLocalLockfileAssemblies>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoWarn>$(NoWarn);IDE1006,CS8618,MSB3270</NoWarn>
    </PropertyGroup>

    <ItemGroup>
    <Content Include="Data\NNeko.png" />
  </ItemGroup>
    <ItemGroup>
        <None Update="NNekoWeaponIcons.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <EmbeddedResource Include="Data\NNeko.png" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Update="DalamudPackager" Version="15.0.0" />
      <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
    </ItemGroup>
</Project>
