name: "Push/PR: Tests"

on:
  push:
    branches: [main]
    paths:
      - "NNekoWeaponIcons/**/*.cs"
      - "NNekoWeaponIcons/**/*.csproj"
      - "NNekoWeaponIcons/**/*.resx"
  pull_request:
    branches: [main]
    paths:
      - "NNekoWeaponIcons/**/*.cs"
      - "NNekoWeaponIcons/**/*.csproj"
      - "NNekoWeaponIcons/**/*.resx"
    types: [ready_for_review, opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_mode: ["Release", "Debug"]
        dalamud-branch: ["release", "stg"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Dalamud
        run: |
          mkdir -p ~/.xlcore/dalamud/Hooks/${{ matrix.dalamud-branch }}
          curl -L https://github.com/goatcorp/dalamud-distrib/raw/master/${{ matrix.dalamud-branch }}/Dalamud.zip -o dalamud.zip
          unzip -o dalamud.zip -d ~/.xlcore/dalamud/Hooks/${{ matrix.dalamud-branch }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Package
        run: dotnet publish --configuration Release
